CREATE DATABASE node_mysql;

USE node_mysql;

CREATE TABLE users
(
    id INT(11) NOT NULL,
    user_name VARCHAR(16) NOT NULL,
    password VARCHAR(60) NOT NULL,
    full_name VARCHAR(100) NOT NULL
);

ALTER TABLE users ADD PRIMARY KEY (id);

ALTER TABLE users MODIFY id INT(11) NOT NULL AUTO_INCREMENT;

DESCRIBE users;

CREATE TABLE links
(
    id INT(11) NOT NULL,
    title VARCHAR(25) NOT NULL,
    url VARCHAR(255) NOT NULL,
    description TEXT(500) NOT NULL,
    user_id INT(11),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id)
);

ALTER TABLE links ADD PRIMARY KEY (id);

ALTER TABLE links MODIFY id INT(11) NOT NULL AUTO_INCREMENT;

DESCRIBE links;